exclude: "(til-template|old-posts)/.*"
repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff-format
        name: nbqa-ruff-format
        description: Run 'ruff format' on a Jupyter Notebook
        entry: nbqa "ruff format"
        language: python
        additional_dependencies: [ruff]
        require_serial: true
        types_or: [jupyter]
      - id: nbqa-isort
        additional_dependencies: [isort]
        name: nbqa-isort
        description: Run 'isort' on a Jupyter Notebook
        entry: nbqa isort
        language: python
        require_serial: true
        types_or: [jupyter]
