project:
  type: website

execute:
  freeze: auto

website:
  title: "chuckpr blog"
  site-url: https://chuckpr.github.io
  repo-url: https://github.com/chuckpr/chuckpr.github.io
  navbar:
    right:
      - text: "posts"
        href: index.qmd
      - text: "til"
        href: til.qmd
      - text: "about"
        href: about.qmd
      - text: "old posts"
        href: old-posts.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/
format:
  html:
    theme: cosmo
