project:
  type: website

execute:
  freeze: auto

website:
  title: "chuckpr blog"
  site-url: https://chuckpr.github.io
  favicon: favicon.ico
  repo-url: https://github.com/chuckpr/chuckpr.github.io
  page-footer:
    background: light
    left: "{{< iconify fa6-regular:copyright label=copyright title=copyright >}} Copyright 2024, Chuck Pepe-Ranney"
    right: This website is built with [{{< iconify ph:github-logo-fill title=GitHub label=GitHub >}}](https://github.com/chuckpr/chuckpr.github.io){target=_blank} and [{{< iconify simple-icons:quarto title=Quarto label=Quarto >}}](https://quarto.org/){target=_blank}
  navbar:
    right:
      - text: "{{< iconify ph:list-bullets-bold title=blog label=label size=Large >}}"
        href: index.qmd
      - text: "{{< iconify ph:lightbulb-bold title=TIL label=TIL size=Large >}}"
        href: til.qmd
      - text: "{{< iconify ph:archive-box-bold title=archive label=archive size=Large >}}"
        href: old-posts.qmd
        aria-label: old posts
      - text: "{{< iconify ph:question-bold title=about label=about size=Large >}}"
        href: about.qmd
      - text: "{{< iconify ph:github-logo-bold label=GitHub title=GitHub size=Large >}}"
        href: https://github.com/chuckpr
      - text: "{{< iconify ph:linkedin-logo-bold title=LinkedIn label=Linkedin size=Large >}}"
        href: https://www.linkedin.com/in/chuckpr/
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    mainfont: "Fira Sans"
    lightbox:
      match: auto
      effect: zoom
    syntax-definitions:
      - fish.xml
    fontsize: 1.15em
    theme:
      - cosmo
      - custom.scss
