[project]
name = "blog"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-64", "osx-arm64"]

[dependencies]
r-rmarkdown = "*"
r-knitr = "*"
r-tidyverse = "*"
r-gt = "*"
r-reticulate = "*"
polars = "*"
great_tables = "*"
nbformat = "*"
pyyaml = "*"
nbclient = ">=0.11.0,<0.12"
jupyterlab = ">=4.6.1,<5"

[tasks]
preview = "quarto preview"
render = "quarto render"
lint = "pre-commit run --all-files"
publish = "quarto publish gh-pages"
